makefile
Added an install instruction for makefile, in order to enable the typical `make`, `sudo make install` installation for Linux.
=> Added make install instruction to install on Linux systems.

util.c
This is prevent unnecessary memcpy() as suggested by @janus in issue #5.
=> Abort ctr_serializer_serialize() early on file error.

citrine.c
=> Prevent segfaulting with -c option and no input.

base.c
- ctr_number_times returns myself
- don't use abs but labs
```
base.c:622:1: warning: control may reach end of non-void function [-Wreturn-type]
}
^
base.c:1059:7: warning: absolute value function 'abs' given an argument of type 'long' but has parameter of type 'int' which may
cause truncation of value [-Wabsolute-value]
b = abs(b);
^
base.c:1059:7: note: use function 'labs' instead
b = abs(b);
^~~
labs
2 warnings generated.
```
=> fix base.c to restrict warnings

world.c
fix to remove `variable 'object' is used uninitialized` warnings.
```
gcc -mtune=native -Wall -c world.c
world.c:753:6: warning: variable 'object' is used uninitialized whenever 'if' condition is true [-Wsometimes-uninitialized]
...o->info.type == CTR_OBJECT_TYPE_OTOBJECT || o->info.type == CTR_OBJECT_TYPE_OTMISC || o->info.type == CTR_OBJECT_TYPE_OTARRAY || o->info.type == CTR_OBJECT_TYPE_OTNIL) {
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
world.c:776:9: note: uninitialized use occurs here
return object;
^~~~~~
world.c:753:2: note: remove the 'if' if its condition is always false
...if (o->info.type == CTR_OBJECT_TYPE_OTOBJECT || o->info.type == …
```
=> fix warnings caused by compiling world.c

runtests.bash
Fix an error in generating shared object
```
+ gcc -shared -o libctrpercolator.so percolator.o
Undefined symbols for architecture x86_64:
"_ctr_build_number_from_float", referenced from:
_ctr_percolator_new in percolator.o
"_ctr_build_string", referenced from:
_ctr_percolator_brew in percolator.o
_ctr_percolator_add_coffee_water in percolator.o
_ctr_percolator_new in percolator.o
_begin in percolator.o
"_ctr_internal_cast2number", referenced from:
_ctr_percolator_add_coffee_water in percolator.o
"_ctr_internal_create_func", referenced from:
_begin in percolator.o
"_ctr_internal_create_object", referenced from:
_ctr_percolator_new in percolator.o
"_ctr_internal_object_add_property", referenced from:
_begin in percolator.o
"_ctr_internal_object_find_property", referenced from: …
```
=> Use undefined dynamic lookup option for darwin platform

mk.bash
This reverts commit 69af8d5adb3795c5bfad8349b9e0b2b00611aa30.
`makefile.macosx` doesn't exist in `master` branch and `makefile` works well in Mac OS X el capitan.
```
% gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/c++/4.2.1
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin15.3.0
Thread model: posix
```
=> Revert "Mac OS X option"

file.c
Some `malloc`-ed `pathString` are not `free`-ed.
=> fix for memory leak

parser.c
Test string length before creating memory to avoid wasting memory.
=> Test string length before creating memory

util.c
```
util.c:197:8: warning: unused variable 'pathName' [-Wunused-variable]
char  pathName[1024];
^
```
=> 'pathName' variable is not used at last

base.c
This docstring? is something wrong.
```
respondTo: [String] with
respondTo: [String] with: [String] and:
```
=> fix respondTo document

file.c
```
file.c:411:6: warning: unused variable 'offset' [-Wunused-variable]
int offset;
^
file.c:438:6: warning: unused variable 'offset' [-Wunused-variable]
int offset;
^
```
=> fix unused variable `offset` in file.c

base.c
While going through the man document I noticed that while describing ordinary multiplication the word "divider" was used instead of "multiplier"
=> Replaced "divider" to "multiplier"

system.c
```
system.c:58:15: warning: unused variable 'map' [-Wunused-variable]
ctr_map*     map = NULL;
^
1 warning generated.
```
=> restrict warning

lexer.c
```
gcc siphash.o utf8.o memory.o util.o base.o collections.o file.o system.o world.o lexer.o parser.o walker.o citrine.o -rdynamic -lm -ldl -o ctr -v
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
"/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld" -demangle -export_dynamic -dynamic -arch x86_64 -macosx_version_min 10.11.0 -o ctr siphash.o utf8.o memory.o util.o base.o collections.o file.o system.o world.o lexer.o parser.o walker.o citrine.o -lm -ldl -lSystem /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.3.0/lib/darwin/libclang_rt.osx.a
Undefined …
```
=> ctr_clex_is_delimiter shouldn't inline (at Darwin)

parser.c, world.c
```
gcc -mtune=native -Wall -c world.c
world.c:266:8: warning: unused variable 'q' [-Wunused-variable]
char* q = calloc( sizeof(char), nlen );
^
```
```
gcc -mtune=native -Wall -c parser.c
parser.c:509:8: warning: unused variable 't' [-Wunused-variable]
int t = ctr_clex_tok();
```
=> remove unused variables warnings

citrine.c
```
citrine.c:81:86: warning: format specifies type 'unsigned long' but the argument has type 'uint64_t' (aka 'unsigned long long')
[-Wformat]
printf( "[WARNING] Citrine has detected an internal memory leak of: %lu bytes.\n", ctr_gc_alloc );
~~~            ^~~~~~~~~~~~
%llu
```
=> remove format specifies type unmatch warning

citrine.c, world.c
This pull request fixes test0156 again, because somehow the addition of the `return` statement in #80 is gone.
This also uses the PRIu64 macro to definitely squash the warning about using the incorrect type, also seen in #82 . On my machine, an unsigned 64 bit integer is `unsigned long` instead of `unsigned long long`. To resolve these differences, there are a number of macros one can use from the inttypes.h header.
=> Remove format warning and fix test0156

citrine.h, collections.c, tests/test0231.ctr, tests/test0231.exp, world.c
Overrides default `type` method from `Object` with an `Array` and `Map` specific string return value.
=> Collection type methods

bin/Haiku/.gitkeep, file.c, system.c
Using d_type with dirents isn't POSIX, and isn't supported by Plan 9 or Haiku― switched to using lstat.
Haiku also complains when using `bool` as a name.
=> Compatibility with Haiku
